### ISSUE TITLE
AttributeError: module 'constants' has no attribute 'version_help_text'

### ISSUE THREAD

**Issue by functicons** [GoogleCloudDataproc/custom-images#37]
```
$ python generate_custom_image.py 
Traceback (most recent call last):
  File "generate_custom_image.py", line 95, in <module>
    main()
  File "generate_custom_image.py", line 86, in main
    args = parse_args(sys.argv[1:])
  File "generate_custom_image.py", line 55, in parse_args
    args = args_parser.parse_args(raw_args)
  File "/usr/local/google/home/dagang/repo/github/functicons/dataproc-custom-images/custom_image_utils/args_parser.py", line 58, in parse_args
    help=constants.version_help_text)
AttributeError: module 'constants' has no attribute 'version_help_text'
```

Seems there is a conflict between the `constants.py` under the `custom_image_utils` folder and the `constants` module from my Python environment. 

```
$ pip freeze | grep constants
constants==0.6.0
```

**Comment by Sawrozzz** [comment]
module constants has now attribute 'APIKEY'  need answer
