### ISSUE TITLE
Script is not working with newer image versions

### ISSUE THREAD

**Issue by richard-williamson** [GoogleCloudDataproc/custom-images#57]
```
08:49:40 DOCKER: INFO:__main__:Parsed args: Namespace(accelerator=None, base_image_uri=None, customization_script='dataproc_image_setup.sh', dataproc_version='2.0.10-debian10', disk_size=32, dry_run=False, extra_sources={}, family='dataproc-custom-image', gcs_bucket='gs://REDACTED', image_name='redacted-05112021-2-0-10-debian10', machine_type='n1-standard-1', maria_version=None, network='', no_external_ip=True, no_smoke_test=True, oauth=None, project_id=None, service_account='default', shutdown_instance_timer_sec=120, subnetwork='redacted', zone='redacted')
08:49:41 DOCKER: INFO:custom_image_utils.args_inferer:Getting Dataproc base image name...
08:49:45 DOCKER: Traceback (most recent call last):
08:49:45 DOCKER:   File "generate_custom_image.py", line 95, in <module>
08:49:45 DOCKER:     main()
08:49:45 DOCKER:   File "generate_custom_image.py", line 86, in main
08:49:45 DOCKER:     args = parse_args(sys.argv[1:])
08:49:45 DOCKER:   File "generate_custom_image.py", line 57, in parse_args
08:49:45 DOCKER:     args_inferer.infer_args(args)
08:49:45 DOCKER:   File "/workspace/samscdp-custom-images/custom_image_utils/args_inferer.py", line 170, in infer_args
08:49:45 DOCKER:     _infer_base_image(args)
08:49:45 DOCKER:   File "/workspace/samscdp-custom-images/custom_image_utils/args_inferer.py", line 137, in _infer_base_image
08:49:45 DOCKER:     args.dataproc_base_image = _get_dataproc_image_path_by_version(args.dataproc_version)
08:49:45 DOCKER:   File "/workspace/samscdp-custom-images/custom_image_utils/args_inferer.py", line 117, in _get_dataproc_image_path_by_version
08:49:45 DOCKER:     raise RuntimeError(
08:49:45 DOCKER: RuntimeError: ('Cannot find dataproc base image with dataproc-version=%s.', '2.0.10-debian10')
```

Appears to be issue with last few images - possibly not having correct labels:
this one works:
```yaml
labels:
  goog-dataproc-base-image: debian-10-buster-v20210217
  goog-dataproc-version: 2-0-6-debian10
```

but newer ones do not:
```yaml
labels:
  goog-dataproc-base-image: debian-10-buster-v20210316
  google-dataproc-version: 2-0-9-debian10
```
Notice different label name  `google-dataproc-version` vs.  `goog-dataproc-version`.

**Comment by medb** [comment]
Thank you for the report, this is a bug that we are going to fix.

**Comment by medb** [comment]
Labels are fixed now.

**Comment by schaffino** [comment]
@medb
This appears to also be the case for the deb10 1.5 images since 1-5-35-debian10. The newer ones don't seem to have labels present

**Comment by medb** [comment]
@schaffino There were few images that we rolled back and didn't apply/removed labels from them. We [just released](https://cloud.google.com/dataproc/docs/release-notes#July_05_2021) a new set of images and will apply labels to them on Monday - this will allow custom image build using these images.
