### ISSUE TITLE
Cannot find dataproc base image

### ISSUE THREAD

**Issue by GregProbst** [GoogleCloudDataproc/custom-images#72]
We are trying to create a new dataproc image using the following paramaters:

```
python generate_custom_image.py \
    --image-name image_name \
    --dataproc-version "1.5.57-debian10" \
    --customization-script ../customization_script.sh \
    --zone us-central1-b \
    --gcs-bucket gs://image-logs \
    --disk-size 50 \
    --machine-type n1-standard-4 \
    --metadata "{ \"spark-jar\": \"$SPARK_JAR\", \"postgres-jar\": \"$POSTGRES_JAR\", \"project\": \"$G_PROJECT\", \"instance-id\": \"$G_BIG_TABLE_INSTANCE\", \"postgres-user\": \"$POSTGRES_USER\", \"postgres-password\": \"$POSTGRES_PASSWORD\", \"postgres-database\": \"$POSTGRES_DATABASE\", \"postgres-host\": \"$POSTGRES_HOST\", \"postgres-port\": \"$POSTGRES_PORT\"}"
```

We are getting an error saying that the dataproc-version could not be found:

```
Traceback (most recent call last):
  File "generate_custom_image.py", line 95, in <module>
    main()
  File "generate_custom_image.py", line 86, in main
    args = parse_args(sys.argv[1:])
  File "generate_custom_image.py", line 57, in parse_args
    args_inferer.infer_args(args)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 225, in infer_args
    _infer_base_image(args)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 191, in _infer_base_image
    args.dataproc_version)
  File "/dataproc-custom-images/custom_image_utils/args_inferer.py", line 175, in _get_dataproc_image_path_by_version
    "Cannot find dataproc base image with dataproc-version=%s." % version)
RuntimeError: Cannot find dataproc base image with dataproc-version=1.5.57-debian10.
```

We have tried several different versions but each one gives the same error. We have looked at the docs and we think we are defining the version correctly. Any guidance would be appreciated.

**Comment by medb** [comment]
`1.5.57-debian10` image will be available as a base for custom image creation in 1 week after its release, meanwhile you can use `1.5.56-debian10` image, or just `1.5-debian10` alias, that will pick up the latest available image.

**Comment by GregProbst** [comment]
We tried both of those as well as other versions. All are giving us the same error.
